### ISSUE TITLE
Can't force updates using topic: update on input

### ISSUE THREAD

**Issue by wonderwareguru** [otaviojr/node-red-contrib-smartthings#1]
Greetings,

First off, I really really appreciate your Smartthings contribution. It means a lot to me, and is a life saver in tying together my z-wave, mqtt, modbus project together. Much respect. My issue involves status updates. Whenever I deploy, the output status / values for smartthings shows in debug... 

"device : msg.payload : Object
object
deviceId: "546fbc2b-fe82-412d-8f04-9133909ebdd2"
deviceType: "contact"
name: "KITCHEN DOOR"
value: 0"

however, when I change the device state, the node-red status does not change, unless I re-deploy.

I read your help statement:
"Besides, if you need it to output the status, like when responding a http request, you can use the topic with the update value to force it to report."

I can't get the update to work for the life of me. I've tried everything and the kitchen sink.

Can you please clarify. With "Inject", I type "update" in the topic field, and leave the payload type "string" and the field blank. Is this correct? 

When I trigger the input I get... 

"update : msg.payload : string[0]"

 in debug, on the output of the smartthings node.

I tried the update in topic for contact, motion... with the same result.

Can you please help... what am I missing.

Thanks a lot.

**Comment by otaviojr** [comment]
Hi,

The update topic on the input will only force the node to output its current state.

The real update will happens through the webhook. Have you installed the smartapp?

The smartapp will listen to all events and send them to NodeRed.

Nodes will them listen for those events to update theirs status 

Are your smartapp/webhook working?

Regards

**Comment by wonderwareguru** [comment]
Hi, 
Thanks for the reply. Your patience is greatly appreciated :)

My nodes are reporting correct events in Node-Red, but the nodes do not automatically update on their own. If I reload Node-Red's HTML, or re-deloy the nodes in Node-Red, the node events update without issue.

You stated that "The update topic on the input will only force the node to output its current state." This is what I'm having an issue with. 

For me, the "update" topic on the input of your node will not force the node to output its current state. It will only if I redeploy or reload the HTML

In order to force the output, do I use an "Inject" node, and type "update" in the topic box? If so, what is also the data type and content of the payload. I believe this is where the issue is.

Can you please give a quick example of how you would set up the input of your node. Are you using Node-Red's "Inject" node? What is the msg.payload for the input of your nodes? 

Thank you Sir.

**Comment by otaviojr** [comment]
Hey, don't worry about that. 

As I'm developing thin, I really want to understand what is going on. 

Right Now, I don't think that the problem it at NodeRed End. I believe that the problem is with smartthings setup.

We can execute some procedures just to make sure that Smartthings Webhook is working all right.

![smartthings_1](https://user-images.githubusercontent.com/2933837/67167032-9518ee00-f36b-11e9-95b2-a7992ff01378.png)

1) Click on **My Locations** and choose the location you want
2) Click on **My Smart apps**

![smartthings_2](https://user-images.githubusercontent.com/2933837/67167044-bc6fbb00-f36b-11e9-862c-b8ca0c10aff2.png)

3) Click at the webhook you created with our smartapp application

![smartthings_3](https://user-images.githubusercontent.com/2933837/67167053-cbef0400-f36b-11e9-83a6-ec246e029bce.png)

4) Start the simulator

![smartthings_4](https://user-images.githubusercontent.com/2933837/67167058-d8735c80-f36b-11e9-91d9-6ff917371a33.png)

5) Set the location to debug
6) Configure the webhook address. It should be your NodeRed public address plus "/smartthings/webhook"

![smartthings_5](https://user-images.githubusercontent.com/2933837/67167070-fa6cdf00-f36b-11e9-89c9-d1c5bbce3c7f.png)

Choose a device, could be a virtual one, which is easier to test.

7) Click **install**

![Screenshot from 2019-10-20 18-56-19](https://user-images.githubusercontent.com/2933837/67167086-21c3ac00-f36c-11e9-9e52-2423792daa4f.png)

Change the device state and look for the logs... if there is any error it will output there. 

Actually, if everything works all right nothing will be logged in.

Sorry about this giant procedure... but this webhook is the one who send update messages to NodeRed. We must be sure it is working all right in order to the node to update correctly..

I thank you to help me to make this code better.

regards,

**Comment by wonderwareguru** [comment]
Hi, Otaviojr
Thanks for the tutorial. I followed it and got errors. Attached are screen shots. When you say 

"Configure the webhook address. It should be your NodeRed public address plus "/smartthings/webhook"" 

- do you mean your LAN ip address, or WAN? I'm tried various combinations my WAN, LAN, and 127.0.0.1... "LANIPADDRESS/smartthings/webhook"

<--------------------------------------->

![Uploading Screen Shot 2019-10-20 at 7.40.58 PM.png…]()
<img width="1412" alt="Screen Shot 2019-10-20 at 7 48 12 PM" src="https://user-images.githubusercontent.com/56791410/67168934-3efd7800-f376-11e9-9673-97603c1954a2.png">

<---------------------------------------->


The following is my NODE-RED setup and issue:

<img width="1071" alt="Screen Shot 2019-10-20 at 7 51 30 PM" src="https://user-images.githubusercontent.com/56791410/67168964-65231800-f376-11e9-815d-1f98d0bb1f8a.png">

<img width="885" alt="Screen Shot 2019-10-20 at 7 50 53 PM" src="https://user-images.githubusercontent.com/56791410/67168968-694f3580-f376-11e9-9568-777361c8fbef.png">

Any ideas about forcing the update? 

Thanks

**Comment by otaviojr** [comment]
1) If we make the webhook works, you will not need the update node. It's correct, but the device will receive a message from smartthings and output the updated state. This is only useful when you want to get the status without an event from smartthings.

2) Without the webhook the behavior is all right. The device will update at the deploy to have the initial state. After that only when it receives messages from SmartThings webhook. 

2) About the error, SmartThings have some rules. One of them is, the SmartApp is not executed in the hub, but in the cloud. Outside your local network. So, it must be publicly acessible. Like a domain, for example. I will check if there are any way to perform it from the hub, but, SmartThings doesn't like that too much..

We need to focus on how make the webhook works (solve those console errors). They will make the device node update and output the message as soon as they have been changed.

regards

**Comment by wonderwareguru** [comment]
Otaviojr, I'm confused, where can I find the public IP address? https://xxx.xxx.xxx.xxx/smartthings/webhook?

**Comment by otaviojr** [comment]
I have done a new option at smartapp configuration.

It will have now a local network option.

You can check that and use your local address:

http://192.168.0.xx/smartthings/webhook.

Can you get the new smartapp from github?

regards

**Comment by otaviojr** [comment]
you can find it here:

[SmartApp]https://github.com/otaviojr/node-red-contrib-smartthings/blob/master/smartapp/webhook.groovy)

**Comment by otaviojr** [comment]
Hey @wonderwareguru, did you test the new smartapp. Did it work?

**Comment by wonderwareguru** [comment]
Hey brother... sorry, I have been unable to test yet. I'm going to test in an hour or so...

Thanks

**Comment by wonderwareguru** [comment]
OK, I got it working. Do not change anything. I'll take some time later this evening to document (pics, video) how I set it up and I'll post it to this thread. 

Thanks...

**Comment by Tokter** [comment]
I followed these steps trying to debug the same issue.
What I missed was that I didn't select the switch in the smartapp. I assumed all events would be forwarded to node red. Once I selected the switch in the "Choose what events you want to trigger" section, everything is working.
Thanks for you great work!

**Comment by mpkayeuk** [comment]
I'm having exactly this issue, with the Local Network Call.  It updates when I deploy, but not with an injected update.  Also, I can't get injectors to change the state of even a simple switch device.  When I do the simulation step, the simulator appears to work perfectly!

**Comment by mane-wt** [comment]
If you add the port, it will work, http://192.168.0.xx:1880/smartthings/webhook.
The thing left for me is the inject-node with update that does not work. I have put topic=update and tried with different payloads but all I get throuch is the same msg passed trough with the same topic/payload as I entered for input. If topic <> update, nothing goes through.

**Comment by mane-wt** [comment]
I can add that the IKEA button battery delivers the battery percentage OK in the Battery-node

**Comment by otaviojr** [comment]
You can not force update by this way. It will update automatically when anything change. This is what the smartapp does.

You can send message to the node to change its state. For example, turn on a switch.

When you deploy it will update, after that, when anything change, the smartapp will send the new state to the node. So, there is no need to force update it.

regards,
Otávio Ribeiro

**Comment by mane-wt** [comment]
OK, really no need to force update anyway.

The other problem still remain with the motion sensors from IKEA.
In more detail:

My flow looks like: 
![Flow](https://user-images.githubusercontent.com/30109811/71541809-e2629e80-295e-11ea-8940-eaa4f56c4370.jpg)

And the motion nodes:
![2019-12-28 10-31-15](https://user-images.githubusercontent.com/30109811/71541816-f4dcd800-295e-11ea-9671-f8b77c28eb51.jpg)
![2019-12-28 10-32-26](https://user-images.githubusercontent.com/30109811/71541818-f73f3200-295e-11ea-9f0e-c3e5c8465b9f.jpg)

When I deploy, both generates output:
![Deploy](https://user-images.githubusercontent.com/30109811/71541821-045c2100-295f-11ea-98b1-88877591ddaf.jpg)

With movement I only get output from Samsung Motion Sensor, not IKEA:
![Motion](https://user-images.githubusercontent.com/30109811/71541837-2190ef80-295f-11ea-807b-f5d93586a6d5.jpg)

I got output in the Samsung SmartThings App in the mobile for both sensors, here IKEA:
![IKEA rörelse](https://user-images.githubusercontent.com/30109811/71541851-50a76100-295f-11ea-9293-30eefcfae35e.jpg)

And after a few seconds:
![IKEA ingen rörelse](https://user-images.githubusercontent.com/30109811/71541854-543ae800-295f-11ea-95c7-5f565bf58f8b.jpg)

The only difference I have seen between the sensors is that Samsung has build in temperature, and IKEA have not but this probably does not matter with this node that only looks at motion.

Any idéas?

BR
Magnus

**Comment by otaviojr** [comment]
Above, in this thread have some steps to debug the SmartApp. Could you debug it with the IKEA device selected? Than we can see if there are any problem with the IKEA device which is preventing the SmartApp from sending the update message.

Have you tried to play with the name of the device? Shorten it, remove the special character, etc? These are the only difference I saw right now.

If you help me to understand this problem I can fix it. Unfortunately I don't have any IKEA device. Have many motion sensors, but no one from them.

regards,
Otavio Ribeiro

**Comment by mane-wt** [comment]
Thanks for the offered help!

I have shortened and removed the special characters so the new name is "IKEA Motion Sensor" but unfortunately that was not the issue.

I will now try the debug steps and report back.

BR
Magnus

**Comment by mane-wt** [comment]
Some debugging done now.

The debug output look very similiar with Samsung and IKEA motion sensors:
Samsung debug "gear"
![Samsung motion sensor gear](https://user-images.githubusercontent.com/30109811/71555698-38067c00-2a2f-11ea-923a-9c83977e21ff.jpg)

IKEA debug "gear"
![IKEA motion sensor gear](https://user-images.githubusercontent.com/30109811/71555780-d5fa4680-2a2f-11ea-9189-683047e871d4.jpg)

Samsung debug:
![Samsung motion sensor debug 2](https://user-images.githubusercontent.com/30109811/71555817-41441880-2a30-11ea-95e1-2c1400745a14.jpg)

IKEA debug:
![IKEA motion sensor debug 2](https://user-images.githubusercontent.com/30109811/71555823-4e610780-2a30-11ea-9db4-482472d371f9.jpg)

Live logging reveals:
![Live Logging](https://user-images.githubusercontent.com/30109811/71555834-66388b80-2a30-11ea-9ffc-ad41bd8cbaec.jpg)

One strange thing I found was that my IKEA sensor is not in this list:
![Event subscriptions](https://user-images.githubusercontent.com/30109811/71555850-91bb7600-2a30-11ea-9262-954d5e9b57da.jpg)

BR
Magnus

**Comment by otaviojr** [comment]
Just to put us on the same page.

Do you have the classical SmartThings app installed?

On Automation -> SmartApps -> NodeRed -> Motion Sensor section, do the IKEA device appears on the list, is it selected?

It not being selected could explain why it is not appearing at event list.

Regards,
Otávio Ribeiro

**Comment by mane-wt** [comment]
Thats it!!

For some reason only some of my sensors where selected, it looked like:
![Screenshot_20191229-184313_SmartThings](https://user-images.githubusercontent.com/30109811/71561637-52654780-2a79-11ea-94c0-cbc16353bbe5.jpg)
After ticking the box the motion sensors worked flawlessly, thank you!

I checked all the sensors in this view and tested the IKEA Button.
![Flow](https://user-images.githubusercontent.com/30109811/71561653-7c1e6e80-2a79-11ea-80eb-6c36c6137e4b.jpg)

This also worked but I got several "red"-marked output in Node-Red debug window with only one klick on the IKEA button:
![IKEA Remote button](https://user-images.githubusercontent.com/30109811/71561660-a112e180-2a79-11ea-8506-7ddcface3b10.jpg)

The last 2 messages expanded:
![Expanded](https://user-images.githubusercontent.com/30109811/71561661-b720a200-2a79-11ea-9e68-8985cf8bf89e.jpg)

In Samsungs Debug I got the same as with the motion sensor.

In Samsungs Live Debug I got:
![IKEA Live Debug](https://user-images.githubusercontent.com/30109811/71561664-c6075480-2a79-11ea-832e-33f909df3b42.jpg)

It works but the red-marking is a bit anoying. Could it be debug-text from the Node-Red node itself or can I just ignore this?

BR
Magnus

**Comment by otaviojr** [comment]
Those messages are mine. I’output them from inside the plugin. They can help me to debug when things goes wrong. As the code gets more mature I will remove them. For now, just ignore them.

Regards,
Otávio Ribeiro

**Comment by mane-wt** [comment]
Thank you very much for the help :-)

I will try to use my Samsung Airconditioner and see how that works with your nodes next.

BR
Magnus
