### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Tsaaek** [otaviojr/node-red-contrib-smartthings#10]
Hello!
I am unable to install.

```
`pi@raspberrypi:~ $ npm install node-red-contrib-smartthings
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/otaviojr/smartthing          s-node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-16T17_57_40_684Z-debug.log
`
```

**Comment by otaviojr** [comment]
It's working here.

Can you post the content of this file:
/home/pi/.npm/_logs/2019-12-16T17_57_40_684Z-debug.log

regards,
Otávio Ribeiro

**Comment by Tsaaek** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-smartthings' ]
2 info using npm@6.13.4
3 info using node@v10.17.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose npm-session 175a8e3a1a24c857
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-smartthings 490ms (from cache)
9 silly pacote tag manifest for node-red-contrib-smartthings@latest fetched in 703ms
10 timing stage:loadCurrentTree Completed in 10400ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 75ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 4743ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule node-red-contrib-smartthings@0.0.11 checking installable status
18 silly tarball trying https://registry.npmjs.org/node-red-contrib-smartthings/-/node-red-contrib-smartthings-0.0.11.tgz by hash: sha512-FSXyA8UrE9nxEnHoJnDhj0K0Xq8IfGRuj9q/1DEOOqfEjPy1KT$
19 silly extract https://registry.npmjs.org/node-red-contrib-smartthings/-/node-red-contrib-smartthings-0.0.11.tgz extracted to /tmp/npm-665-4131bbde/unpack-b2e1bb8f (1527ms)
20 silly addBundled read tarball
21 silly cleanup remove extracted module
22 silly fetchPackageMetaData error for smartthings-node@git+https://github.com/otaviojr/smartthings-node.git Error while executing:
22 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/otaviojr/smartthings-node.git
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData spawn git ENOENT
23 http fetch GET 304 https://registry.npmjs.org/jsbn 3976ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/http-signature 3877ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/promise 4030ms (from cache)
26 silly pacote range manifest for jsbn@^1.1.0 fetched in 4151ms
27 silly resolveWithNewModule jsbn@1.1.0 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/axios 4022ms (from cache)
29 silly pacote range manifest for http-signature@* fetched in 4085ms
30 silly resolveWithNewModule http-signature@1.3.1 checking installable status
31 silly pacote range manifest for promise@^8.0.3 fetched in 4242ms
32 silly resolveWithNewModule promise@8.0.3 checking installable status
33 silly pacote range manifest for axios@* fetched in 4160ms
34 silly resolveWithNewModule axios@0.19.0 checking installable status
35 timing stage:rollbackFailedOptional Completed in 12ms
36 timing stage:runTopLevelLifecycles Completed in 21851ms
37 silly saveTree pi
37 silly saveTree pi
37 silly saveTree ├─┬ abstract-things@0.9.0
37 silly saveTree │ ├── amounts@0.5.0
37 silly saveTree │ ├── appdirectory@0.1.0
37 silly saveTree │ ├─┬ color-convert@1.9.3
37 silly saveTree │ │ └── color-name@1.1.3
37 silly saveTree │ ├─┬ color-string@1.5.3
37 silly saveTree │ │ └─┬ simple-swizzle@0.2.2
37 silly saveTree │ │   └── is-arrayish@0.3.2
37 silly saveTree │ ├── color-temperature@0.2.7
37 silly saveTree │ ├─┬ debug@3.2.6
37 silly saveTree │ │ └── ms@2.1.2
37 silly saveTree │ ├─┬ deep-equal@1.1.1
37 silly saveTree │ │ ├── is-arguments@1.0.4
37 silly saveTree │ │ ├── is-date-object@1.0.1
37 silly saveTree │ │ ├─┬ is-regex@1.0.5
37 silly saveTree │ │ │ └─┬ has@1.0.3
37 silly saveTree │ │ │   └── function-bind@1.1.1
37 silly saveTree │ │ ├── object-is@1.0.2
37 silly saveTree │ │ ├── object-keys@1.1.1
37 silly saveTree │ │ └─┬ regexp.prototype.flags@1.3.0
37 silly saveTree │ │   ├── define-properties@1.1.3
37 silly saveTree │ │   └─┬ es-abstract@1.17.0-next.1
37 silly saveTree │ │     ├─┬ es-to-primitive@1.2.1
37 silly saveTree │ │     │ ├── is-callable@1.1.4
37 silly saveTree │ │     │ └─┬ is-symbol@1.0.3
37 silly saveTree │ │     │   └── has-symbols@1.0.1
37 silly saveTree │ │     ├── has-symbols@1.0.1
37 silly saveTree │ │     ├── is-callable@1.1.4
37 silly saveTree │ │     ├── object-inspect@1.7.0
37 silly saveTree │ │     ├── object.assign@4.1.0
37 silly saveTree │ │     ├── string.prototype.trimleft@2.1.0
37 silly saveTree │ │     └── string.prototype.trimright@2.1.0
37 silly saveTree │ ├─┬ dwaal@0.1.4
37 silly saveTree │ │ ├─┬ end-of-stream@1.4.4
37 silly saveTree │ │ │ └─┬ once@1.4.0
37 silly saveTree │ │ │   └── wrappy@1.0.2
37 silly saveTree │ │ ├─┬ fs-write-stream-atomic@1.0.10
37 silly saveTree │ │ │ ├── graceful-fs@4.2.3
37 silly saveTree │ │ │ ├── iferr@0.1.5
37 silly saveTree │ │ │ ├── imurmurhash@0.1.4
37 silly saveTree │ │ │ └─┬ readable-stream@2.3.6
37 silly saveTree │ │ │   ├── core-util-is@1.0.2
37 silly saveTree │ │ │   ├── inherits@2.0.4
37 silly saveTree │ │ │   ├── isarray@1.0.0
37 silly saveTree │ │ │   ├── process-nextick-args@2.0.1
37 silly saveTree │ │ │   ├── safe-buffer@5.1.2
37 silly saveTree │ │ │   ├── string_decoder@1.1.1
37 silly saveTree │ │ │   └── util-deprecate@1.0.2
37 silly saveTree │ │ ├─┬ msgpack-lite@0.1.26
37 silly saveTree │ │ │ ├── event-lite@0.1.2
37 silly saveTree │ │ │ ├── ieee754@1.1.13
37 silly saveTree │ │ │ └── int64-buffer@0.1.10
37 silly saveTree │ │ ├── msgpack-sock@1.1.0
37 silly saveTree │ │ └─┬ unix-socket-leader@0.1.2
37 silly saveTree │ │   └── pidlockfile@1.1.1
37 silly saveTree │ ├── foibles@0.2.0
37 silly saveTree │ ├── is-mergeable-object@1.1.1
37 silly saveTree │ ├─┬ mkdirp@0.5.1
37 silly saveTree │ │ └── minimist@0.0.8
37 silly saveTree │ └─┬ tinkerhub-discovery@0.3.1
37 silly saveTree │   └── eventemitter3@2.0.3
37 silly saveTree ├── amounts@0.5.0
37 silly saveTree ├── ansi-regex@3.0.0
37 silly saveTree ├── ansi-styles@3.2.1
37 silly saveTree ├── appdirectory@0.1.0
37 silly saveTree ├─┬ bootstrap-multiselect@0.9.15
37 silly saveTree │ └── jquery@2.1.4
37 silly saveTree ├── camelcase@4.1.0
37 silly saveTree ├─┬ chalk@2.4.2
37 silly saveTree │ ├── escape-string-regexp@1.0.5
37 silly saveTree │ └─┬ supports-color@5.5.0
37 silly saveTree │   └── has-flag@3.0.0
37 silly saveTree ├─┬ cliui@4.1.0
37 silly saveTree │ ├─┬ string-width@2.1.1
37 silly saveTree │ │ ├── is-fullwidth-code-point@2.0.0
37 silly saveTree │ │ └── strip-ansi@4.0.0
37 silly saveTree │ ├── strip-ansi@4.0.0
37 silly saveTree │ └─┬ wrap-ansi@2.1.0
37 silly saveTree │   ├─┬ string-width@1.0.2
37 silly saveTree │   │ ├── code-point-at@1.1.0
37 silly saveTree │   │ ├─┬ is-fullwidth-code-point@1.0.0
37 silly saveTree │   │ │ └── number-is-nan@1.0.1
37 silly saveTree │   │ └─┬ strip-ansi@3.0.1
37 silly saveTree │   │   └── ansi-regex@2.1.1
37 silly saveTree │   └── strip-ansi@3.0.1
37 silly saveTree ├── code-point-at@1.1.0
37 silly saveTree ├── color-convert@1.9.3
37 silly saveTree ├── color-name@1.1.3
37 silly saveTree ├── color-string@1.5.3
37 silly saveTree ├── color-temperature@0.2.7
37 silly saveTree ├── core-util-is@1.0.2
37 silly saveTree ├─┬ cross-spawn@5.1.0
37 silly saveTree │ ├─┬ lru-cache@4.1.5
37 silly saveTree │ │ ├── pseudomap@1.0.2
37 silly saveTree │ │ └── yallist@2.1.2
37 silly saveTree │ ├─┬ shebang-command@1.2.0
37 silly saveTree │ │ └── shebang-regex@1.0.0
37 silly saveTree │ └─┬ which@1.3.1
37 silly saveTree │   └── isexe@2.0.0
37 silly saveTree ├── debug@3.2.6
37 silly saveTree ├── decamelize@1.2.0
37 silly saveTree ├── deep-equal@1.1.1
37 silly saveTree ├── define-properties@1.1.3
37 silly saveTree ├── dwaal@0.1.4
37 silly saveTree ├── end-of-stream@1.4.4
37 silly saveTree ├── es-abstract@1.17.0-next.1
37 silly saveTree ├── es-to-primitive@1.2.1
37 silly saveTree ├── escape-string-regexp@1.0.5
37 silly saveTree ├── event-lite@0.1.2
37 silly saveTree ├── eventemitter3@2.0.3
37 silly saveTree ├── events@3.0.0
37 silly saveTree ├─┬ execa@0.7.0
37 silly saveTree │ ├── get-stream@3.0.0
37 silly saveTree │ ├── is-stream@1.1.0
37 silly saveTree │ ├─┬ npm-run-path@2.0.2
37 silly saveTree │ │ └── path-key@2.0.1
37 silly saveTree │ ├── p-finally@1.0.0
37 silly saveTree │ ├── signal-exit@3.0.2
37 silly saveTree │ └── strip-eof@1.0.0
37 silly saveTree ├─┬ find-up@2.1.0
37 silly saveTree │ └─┬ locate-path@2.0.0
37 silly saveTree │   ├─┬ p-locate@2.0.0
37 silly saveTree │   │ └─┬ p-limit@1.3.0
37 silly saveTree │   │   └── p-try@1.0.0
37 silly saveTree │   └── path-exists@3.0.0
37 silly saveTree ├── foibles@0.2.0
37 silly saveTree ├── fs-write-stream-atomic@1.0.10
37 silly saveTree ├── function-bind@1.1.1
37 silly saveTree ├── get-caller-file@1.0.3
37 silly saveTree ├── get-stream@3.0.0
37 silly saveTree ├── graceful-fs@4.2.3
37 silly saveTree ├── has-flag@3.0.0
37 silly saveTree ├── has-symbols@1.0.1
37 silly saveTree ├── has@1.0.3
37 silly saveTree ├── ieee754@1.1.13
37 silly saveTree ├── iferr@0.1.5
37 silly saveTree ├── imurmurhash@0.1.4
37 silly saveTree ├── inherits@2.0.4
37 silly saveTree ├── int64-buffer@0.1.10
37 silly saveTree ├── invert-kv@1.0.0
37 silly saveTree ├── is-arguments@1.0.4
37 silly saveTree ├── is-arrayish@0.3.2
37 silly saveTree ├── is-callable@1.1.4
37 silly saveTree ├── is-date-object@1.0.1
37 silly saveTree ├── is-fullwidth-code-point@2.0.0
37 silly saveTree ├── is-mergeable-object@1.1.1
37 silly saveTree ├── is-regex@1.0.5
37 silly saveTree ├── is-stream@1.1.0
37 silly saveTree ├── is-symbol@1.0.3
37 silly saveTree ├── isarray@1.0.0
37 silly saveTree ├── isexe@2.0.0
37 silly saveTree ├── jquery@2.1.4
37 silly saveTree ├── lcid@1.0.0
37 silly saveTree ├── locate-path@2.0.0
37 silly saveTree ├── lru-cache@4.1.5
37 silly saveTree ├─┬ mem@1.1.0
37 silly saveTree │ └── mimic-fn@1.2.0
37 silly saveTree ├─┬ miio@0.15.6
37 silly saveTree │ └─┬ yargs@10.1.2
37 silly saveTree │   ├── os-locale@2.1.0
37 silly saveTree │   ├── require-directory@2.1.1
37 silly saveTree │   ├── require-main-filename@1.0.1
37 silly saveTree │   ├── set-blocking@2.0.0
37 silly saveTree │   ├── which-module@2.0.0
37 silly saveTree │   ├── y18n@3.2.1
37 silly saveTree │   └── yargs-parser@8.1.0
37 silly saveTree ├── mimic-fn@1.2.0
37 silly saveTree ├── minimist@0.0.8
37 silly saveTree ├── mkdirp@0.5.1
37 silly saveTree ├── moment@2.24.0
37 silly saveTree ├── ms@2.1.2
37 silly saveTree ├── msgpack-lite@0.1.26
37 silly saveTree ├── msgpack-sock@1.1.0
37 silly saveTree ├── node-red-contrib-miio-roborock@1.1.2
37 silly saveTree ├─┬ node-red-contrib-smartthings@0.0.11
37 silly saveTree │ ├── axios@0.19.0
37 silly saveTree │ ├── http-signature@1.3.1
37 silly saveTree │ ├── jsbn@1.1.0
37 silly saveTree │ └── promise@8.0.3
37 silly saveTree ├── npm-run-path@2.0.2
37 silly saveTree ├── number-is-nan@1.0.1
37 silly saveTree ├── object-inspect@1.7.0
37 silly saveTree ├── object-is@1.0.2
37 silly saveTree ├── object-keys@1.1.1
37 silly saveTree ├── object.assign@4.1.0
37 silly saveTree ├── once@1.4.0
37 silly saveTree ├── os-locale@2.1.0
37 silly saveTree ├── p-finally@1.0.0
37 silly saveTree ├── p-limit@1.3.0
37 silly saveTree ├── p-locate@2.0.0
37 silly saveTree ├── p-try@1.0.0
37 silly saveTree ├── path-exists@3.0.0
37 silly saveTree ├── path-key@2.0.1
37 silly saveTree ├── pidlockfile@1.1.1
37 silly saveTree ├── process-nextick-args@2.0.1
37 silly saveTree ├── pseudomap@1.0.2
37 silly saveTree ├── readable-stream@2.3.6
37 silly saveTree ├── regexp.prototype.flags@1.3.0
37 silly saveTree ├── require-directory@2.1.1
37 silly saveTree ├── require-main-filename@1.0.1
37 silly saveTree ├── safe-buffer@5.1.2
37 silly saveTree ├── set-blocking@2.0.0
37 silly saveTree ├── shebang-command@1.2.0
37 silly saveTree ├── shebang-regex@1.0.0
37 silly saveTree ├── signal-exit@3.0.2
37 silly saveTree ├── simple-swizzle@0.2.2
37 silly saveTree ├── string_decoder@1.1.1
37 silly saveTree ├── string-width@2.1.1
37 silly saveTree ├── string.prototype.trimleft@2.1.0
37 silly saveTree ├── string.prototype.trimright@2.1.0
37 silly saveTree ├── strip-ansi@4.0.0
37 silly saveTree ├── strip-eof@1.0.0
37 silly saveTree ├── supports-color@5.5.0
37 silly saveTree ├── tinkerhub-discovery@0.3.1
37 silly saveTree ├── unix-socket-leader@0.1.2
37 silly saveTree ├── util-deprecate@1.0.2
37 silly saveTree ├── which-module@2.0.0
37 silly saveTree ├── which@1.3.1
37 silly saveTree ├── wrap-ansi@2.1.0
37 silly saveTree ├── wrappy@1.0.2
37 silly saveTree ├── y18n@3.2.1
37 silly saveTree ├── yallist@2.1.2
37 silly saveTree ├── yargs-parser@8.1.0
37 silly saveTree └── yargs@10.1.2
38 verbose stack Error: spawn git ENOENT
38 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
38 verbose stack     at onErrorNT (internal/child_process.js:415:16)
38 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
39 verbose cwd /home/pi
40 verbose Linux 4.19.75+
41 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-smartthings"
42 verbose node v10.17.0
43 verbose npm  v6.13.4
44 error code ENOENT
45 error syscall spawn git
46 error path git
47 error errno ENOENT
48 error enoent Error while executing:
48 error enoent undefined ls-remote -h -t https://github.com/otaviojr/smartthings-node.git
48 error enoent
48 error enoent
48 error enoent spawn git ENOENT
49 error enoent This is related to npm not being able to find a file.
50 verbose exit [ 1, true ]
`

**Comment by otaviojr** [comment]
as far as I can see the problem lies with this line:
undefined ls-remote -h -t https://github.com/otaviojr/smartthings-node.git

do you have git installed?

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
It was that?

Did you manage to make it works?

Regards

**Comment by Tsaaek** [comment]
Sorry, I forgot to update. I didn't have git installed. That was the problem. 
Thank you for your help.
