### ISSUE TITLE
Unable to retrieve devices from Smartthings

### ISSUE THREAD

**Issue by xraken** [otaviojr/node-red-contrib-smartthings#11]
I followed the install instructions but when I try to set up the first node with the SmartThings token I don't know if it is working. I expected the "Device" drop-down to populate with the devices discovered from SmartThings (of that particular type) but it keeps saying "Loading" and it never populates.
Not sure what I could be doing wrong. Are there any logs that I can look at?

Also, I have the node red instance running locally on a raspberry pi, when I get to the webhook set up on the Smartthings app should I specify port 1880 or is it just  "http://192.168.1.155/smartthings/webhook" ? If the port is defaulted to 80, how can I change it ot a non-default port (I'm using 80 for something else)?

Thanks

**Comment by burtonjk** [comment]
You will need to deploy a node before it populates your Smartthings in the dropdown.

You need to specify the port, eg: http://192.168.1.155:1880/smartthings/webhook

Hope this helps

**Comment by xraken** [comment]
Got it working, thanks!

**Comment by mane-wt** [comment]
Thanx, that was the solution for me too!
