### ISSUE TITLE
Inconsistency on temperature reporting

### ISSUE THREAD

**Issue by chacques** [otaviojr/node-red-contrib-smartthings#14]
Hi,

There is inconsistency on temperature reports between normal update and forced update.

I am using latest release (0.15).

Normal update reports temperature as float, but forced update reports temperature as string. I think float would be preferred format in both cases.

Device normal report:
{"deviceId":"xxx","deviceType":"temperature","name":"Smoke Sensor Downstairs","value":23.3,"unit":"C"}

Forced update:
{"deviceId":"xxx","deviceType":"temperature","name":"Smoke Sensor Downstairs","value":"23.3","unit":"C"}

Kind regards,
Juha

**Comment by otaviojr** [comment]
fixed on 0.0.16

**Comment by chacques** [comment]
> fixed on 0.0.16

Works now. Thanks :)
