### ISSUE TITLE
Can't get events?

### ISSUE THREAD

**Issue by PiRune** [otaviojr/node-red-contrib-smartthings#17]
I installed using `npm install node-red-contrib-smartthings`

I have followed the 11 steps and installed the smartApp from code. Set it up for local control and even tried the simulator:

![Skærmbillede 2020-01-11 kl  23 49 33](https://user-images.githubusercontent.com/20454469/72211524-1dbbac00-34cd-11ea-908f-480111ee318f.png)

and I get this (which I assume is ok for non-virtual buttons):

![Skærmbillede 2020-01-11 kl  23 51 10](https://user-images.githubusercontent.com/20454469/72211540-5fe4ed80-34cd-11ea-825b-d0b06bdc7ab3.png)

And the devices (wemo switch and IKEA remote) are available in the Node-RED nodes:

![Skærmbillede 2020-01-11 kl  23 55 08](https://user-images.githubusercontent.com/20454469/72211575-d8e44500-34cd-11ea-9548-3068a796c46e.png)

But I can't get any events in Node-RED and I can't control any devices. Also, the examples don't seem to be working:

![Skærmbillede 2020-01-11 kl  23 56 49](https://user-images.githubusercontent.com/20454469/72211588-121cb500-34ce-11ea-8053-14da4afae7c9.png)

What am I missing? Why isn't it working? Any help is greatly appreciated :)

**Comment by PiRune** [comment]
Progress! After updating the node to 0.0.15. I can now get status and control my devices from Node-RED, using these payloads:

update:
![Skærmbillede 2020-01-12 kl  10 47 01](https://user-images.githubusercontent.com/20454469/72217242-11b30700-352c-11ea-96fe-4305d130e8c7.png)

turn on:
![Skærmbillede 2020-01-12 kl  11 09 09](https://user-images.githubusercontent.com/20454469/72217245-1677bb00-352c-11ea-9151-d49fe1cf9807.png)

However, I'm still not getting any events from the buttons/input devices:

![Skærmbillede 2020-01-12 kl  11 13 35](https://user-images.githubusercontent.com/20454469/72217293-a87fc380-352c-11ea-9830-80438e554479.png)

**Comment by otaviojr** [comment]
Could you try to prefix your webhook URL with http://

**Comment by PiRune** [comment]
Thank you for your response 😊 I think I already tried that, but will try again. Just thought that that couldn’t be the issue since I am able to send commands to the devices and get status. I assume that I only need to change this in the url in the SmartThings app?

**Comment by otaviojr** [comment]
Yes.

Em seg, 13 de jan de 2020 06:59, PiRune <notifications@github.com> escreveu:

**Comment by PiRune** [comment]
Just tried it, but with no luck. Both in the app and in the simulator
![Skærmbillede 2020-01-13 kl  23 12 48](https://user-images.githubusercontent.com/20454469/72296663-7a989d00-365a-11ea-8de8-e2dd39e11565.png)

I can control the connected devices via Node-RED, but not get any events when I push a button. I even bought a SmartThings button to make sure that the issue was not with the IKEA remote, but still no events...

![Skærmbillede 2020-01-13 kl  23 13 42](https://user-images.githubusercontent.com/20454469/72296721-98660200-365a-11ea-9a80-7e27abc619c4.png)

**Comment by otaviojr** [comment]
Is your nodered install listening on port 80? Or 1880?

If it is listening at 1880 the address should be:

http://192.168.3.6:1880/smartthings/webhook

Regards

**Comment by PiRune** [comment]
That was it. It worked! YES! Thank you very very much :)

![Skærmbillede 2020-01-14 kl  18 12 30](https://user-images.githubusercontent.com/20454469/72365938-89825c80-36f9-11ea-9eb6-c8ab438ac281.png)

**Comment by otaviojr** [comment]
Good news!!!!!
