### ISSUE TITLE
No Temperature Node

### ISSUE THREAD

**Issue by evilandrex** [otaviojr/node-red-contrib-smartthings#18]
I seem to have lost the temperature node. 

https://i.imgur.com/OziUi4Q.png

I lost it when I updated from an older version of this project to the latest.

**Comment by otaviojr** [comment]
You are right. I lost it too.

Don't worry. I will fix it and publish a new version in a couple of hours.

Thanks

**Comment by otaviojr** [comment]
It's back on 0.0.18 version.

Could you please give it a try?

regards...
