### ISSUE TITLE
Feature request: water sensor

### ISSUE THREAD

**Issue by chacques** [otaviojr/node-red-contrib-smartthings#19]
Hi,

Would it be possible to do Water Leak Sensor -node?

I think Smartapp already has configuration for it (Water sensor), but I think there is no node for it?

Kind Regards,
Juha

**Comment by otaviojr** [comment]
Ok, give me a couple of days.

But, I don't have water leak sensors, so, I will be glad if you could help me testing it.

regards

**Comment by chacques** [comment]
I have water leak sensors and also smoke alarms. I can test them both.

These don't have much use for everyday automation, but nodes can be used to send email alerts, turn lights on and things like that when needed.

**Comment by otaviojr** [comment]
Done... version 0.0.20.

**Comment by u076894** [comment]
Otávio,
Such fast response! Thank you.

I tried deploying. It works. I'll update to 0.0.20 today.

Many thanks! You're doing great work.

Regards,
Russ in Michigan

**Comment by chacques** [comment]
> Done... version 0.0.20.
> 
> The water sensor.... I will work on the smoke sensor...

Tested (with real water): works just like it should. Reports "dry" when dry and "wet" when wet. Reports its state correctly when queried.

It reported immediatly "wet" when I applied water to sensor, and as soon as I cleaned the sensor, it reported "dry". No delay.

**Comment by otaviojr** [comment]
Great news. Until the end of the week I will finish the smoke sensor.

regards
