### ISSUE TITLE
error Installing from npm or UI 

### ISSUE THREAD

**Issue by 53bytes** [otaviojr/node-red-contrib-smartthings#21]
Trying to install this node (latest version) into a node-red version. 1.0.2 running on ubuntu 18.04 and getting Errors trying to install.  I have tried both npm install command line and UI based pallet install, neither work I am getting the following error while trying to install this capability.

/.node-red$ npm install node-red-contrib-smartthings
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/otaviojr/smartthing                                                                           s-node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ab/.npm/_logs/2020-02-05T13_11_19_277Z-debug.log

Full Log file is attached.. 
Appreciate any pointer on how to install this for a project I am working on.
Thanks
[2020-02-05T13_16_13_584Z-debug.log](https://github.com/otaviojr/node-red-contrib-smartthings/files/4159655/2020-02-05T13_16_13_584Z-debug.log)

**Comment by otaviojr** [comment]
Your system is missing git I guess. Could you check if git is installed?

Regards

**Comment by 53bytes** [comment]
thanks yes you are right this fixed the problem..
