### ISSUE TITLE
Is this package a stand-in for a smartthings hub?

### ISSUE THREAD

**Issue by hepcat72** [otaviojr/node-red-contrib-smartthings#23]
I know this is a dumb question, but the answer is not obvious to me.

I have a Raspberry Pi 3 B.  I've been using homebridge for awhile and I've also been playing around with node-red-contrib-homekit-bridged, both of which replace the need for purchasing an apple homekit hub (e.g. a home pod or designating a 4th-gen iDevice as the hub). I'm looking for an analogous version for SmartThings devices because I received a Smartthings button for Christmas and wanted to try it out.  Everything I've read seems to say that you have to purchase a $70 ST hub in order to setup and use the $15 button.

If this package is not such a hub replacement, perhaps you can point me in the direction of a package that does this?  I've been googling this for awhile now and I'm guessing there does not exist a package that can make my Pi act as an ST hub?

**Comment by arkieguy** [comment]
No, this is a package that simply lets you get statuses and control devices on a ST hub.  You still have to have the hub.  Sorry.

**Comment by hepcat72** [comment]
Thanks
