### ISSUE TITLE
mqtt to contact node

### ISSUE THREAD

**Issue by raisingskell** [otaviojr/node-red-contrib-smartthings#25]
This may be a node-red inexperience issue but would appreciate any assistance.

I have contact sensors reporting into node-red via mqtt, works well. I have node-red-smartthings installed, simulator proves connection is good. Native ST devices report status change in node-red.

My goal is to have the mqtt contact sensor node update ST via the OpenClose node. 

[mqtt contact node] -> [OpenClose Node] -> ST. 

Is this possible? The OpenClose node only reports status for what it sees in ST. 

I'm assuming I'll have to convert the string from the mqtt node to an object for the OpenClose node (been at that for hours) and I'll continue working that once I know if my goal is possible. I've read thru the docs and all other posts with no luck. Maybe I'm just too tired to see what's right in front of me.

Much appreciated.

**Comment by nateguru** [comment]
You can write a smart app that you can access from node-red via a http request. You map the endpoints in the smart app. In the smart app, you can call methods in a custom device handler to update the virtual device. I did this with a temperature/humidity sensor mqtt subscription to node-red to smart things. I don't think it is possible to update the device directly, since it doesn't have a command to set the value.

This may help,
https://docs.smartthings.com/en/latest/smartapp-web-services-developers-guide/tutorial-part1.html

This program made it easy to get the bearer token needed for accessing the smart app end point.
https://github.com/BrettSheleski/SmartThings-SmartApp-OAuth-Helper

**Comment by raisingskell** [comment]
Thanks nateguru. The 2 wire points on the smartthings nodes threw me off. I assumed I could wire the mqtt-in node to the left wire point of the open/closed node and that would update ST. Apparently it must be one-way communication from ST to the node only. 

![image](https://user-images.githubusercontent.com/55666784/75629101-33844e00-5bad-11ea-8012-96b13c9aa368.png)

Oh well, back to the drawing board. Thanks for the pointers in those links. I guess its time to start building custom handlers.

**Comment by nateguru** [comment]
I haven't tested these, but here is a simple smart app and device handler. 

[Open Close Device Handler.txt](https://github.com/otaviojr/node-red-contrib-smartthings/files/4272233/Open.Close.Device.Handler.txt)
[Open Close Smart App.txt](https://github.com/otaviojr/node-red-contrib-smartthings/files/4272234/Open.Close.Smart.App.txt)

**Comment by nateguru** [comment]
Example from my mqtt temperature sensor to ST Node Red Flow.

![MQTT to ST Flow](https://user-images.githubusercontent.com/57780394/75631417-b4991080-5bc0-11ea-88b5-a59703da1447.PNG)

**In Set msg.query,**

var baseurl = 'https://\<BASE-URL\>/api/smartapps/installations/\<APP INSTALLATION ID\>/updateTemp/'
msg.query = baseurl + msg.payload.value;
msg.headers = {
    'Authorization': 'Bearer \<TOKEN\>'
}
msg.body = msg.payload;


return msg;


**In http request,** 

Set URL to {{{query}}}

**Comment by sbparsons** [comment]
A bit off topic but @nateguru you mentioned " temperature/humidity sensor mqtt subscription".
I'm looking for temperature sensors with mqtt support - would you mind me asking what devices you have?

**Comment by nateguru** [comment]
> A bit off topic but @nateguru you mentioned " temperature/humidity sensor mqtt subscription".
> I'm looking for temperature sensors with mqtt support - would you mind me asking what devices you have?

I couldn't find one I liked so I ended up getting an Adafruit board with the Sensirion SHT31-D sensor and making my own.  The easiest and cheapest option is connecting it to an esp8266 doing MQTT.

https://www.adafruit.com/category/product/2857

Adafruit also makes a nrf52840 board that has an SHT30 Temp/Humidity sensor, but it would require a BLE to MQTT bridge to get it to MQTT. 

https://www.adafruit.com/product/4516
