### ISSUE TITLE
Can't update heatingSetpoint on HoneywellTCC thermostat

### ISSUE THREAD

**Issue by cspawn1** [otaviojr/node-red-contrib-smartthings#29]
Hi there, I am working on a project where we have 15+ Honeywell TCC thermostats connected to ST. I know that ST has the ability to adjust the heatingSetpoint (since I can change it using the ST app), however I cannot adjust using Node-Red. I have the smartApp added and properly configured and I can grab the current temperature just fine.

I try manually sending a message to the Thermostat using an inject configured to send the following JSON payload:

{
    "topic": "heatingSetpoint",
    "payload": {
        "value": 60
    }
}

However the the Honeywell thermostat will not use the heatingSetpoint of 60.

I am not sure if I have the webhook configured correctly. However, from everything I have seen after reviewing other issues, I don't believe I need the webhook to send changes to the Thermostat node, correct?

**Comment by stofakiller** [comment]
Hi,

I have the same problem, nodered and send mqtt doesnt work, if you change a value in smartthings, get you the changed value in node red? I dont, see my issue #30 

Regards Jan

**Comment by cspawn1** [comment]
I was able to get this working yesterday. I could not get this work work using an inject node directly so ended up using a function node configured like this:

var msg1 = {
    topic: "heatingSetpoint",
    payload: {
        value: 67
    }
}
return msg1;
