### ISSUE TITLE
Node for Presence

### ISSUE THREAD

**Issue by JasonKChow** [otaviojr/node-red-contrib-smartthings#3]
This is a great tool to link everything I have together. I'm moving over from a Smartthings MQTT bridge and something that's missing is a "presence" node. This typically uses phone geolocation to determine if the user is "present" or "away".  It'd be great if we can get a node for that. The device is already selectable in the smartapp.

**Comment by otaviojr** [comment]
Jason,

I pushed a new npm version with the presence sensor.

Could you please give it a try?

I'm unable to test it until sunday. 

regards,

**Comment by JasonKChow** [comment]
Looks like its all good!
