### ISSUE TITLE
Node for thermostat set point

### ISSUE THREAD

**Issue by CopyCat73** [otaviojr/node-red-contrib-smartthings#4]
I can select my thermostat temp sensor as well as the thermostat set point in the smartapp, however there is only a node red node to read temperature, no node to set it. It would be great if you could add it ;) thanks!

**Comment by otaviojr** [comment]
Hi CopyCat, I can do that, but, I can not test it.

I live in Brazil and here we don't need those things. Usually our air conditioning system have only two commands. Coldest possible, or, off. :-)

I will create the node, but, if you could test it will help a lot.

Give me a few days and I send you a message.

regards.

**Comment by otaviojr** [comment]
CopyCat, i pushed a new npm version with the thermostat node.

Could you test it and send me some feedback?

**Comment by CopyCat73** [comment]
I can read the setpoint now from the 4th node:

{ deviceId: "74d2eb6d-6e1e-4495-bc89-e06ce7…", deviceType: "thermostatSetpoint", name: "Thermostaat(thermostat)", value: 19.5 }

However setting a value results in error:

11/3/2019, 5:02:38 PMnode: Thermostaat(thermostat)
msg : string[21]
"Error updating device"
11/3/2019, 5:02:39 PMnode: Thermostaat(thermostat)
msg : error
"TypeError: Cannot convert undefined or null to object"

I'm trying to get some more specific debugging.

**Comment by otaviojr** [comment]
Usually, this error means that your input message is not correct.

Use the debug node to see what’s going inside de node.

It should be something like that:

```
{
  “topic”: “coolingSetPoint|heatingSetPoint”,
  “payload”: {
    “value”: 70
  }
}
```

Regards

**Comment by otaviojr** [comment]
When you click at the node, at info tab, will have examples of all input messages supported.

Regards

**Comment by otaviojr** [comment]
One more thing, you can not set the thermostatSetPoint directly. You need to set the coolingSetPoint or heatingSetPoint. SmartThings will use one or another as thermostatSetPoint depending on when cooling or heating.

Regards

**Comment by otaviojr** [comment]
CopyCat, dit it work? Using collingSetPoint and heatingSetPoint?

**Comment by cspawn1** [comment]
Hi, I am working on a project that will be integrating a number of thermostat nodes. I'll need to adjust heatingSetpoint and coolingSetpoints. I am struggling getting the heatingSetpoint/coolingSetpoint to change. I am just trying to test using the inject node with a JSON message following your example in the thermostat node info. Did you ever get this working with CopyCat?

**Comment by cspawn1** [comment]
Also, do you possibly have an example flow showing how we can utilize the thermostat node?
