### ISSUE TITLE
not connected to node red

### ISSUE THREAD

**Issue by alphabravocharly72** [otaviojr/node-red-contrib-smartthings#45]
Hello,
I have a problem with the integration in node red.
In the Simulator all is working.
Attached a debug screenshot.
What is wrong?
Thank you for helping
alpha
![debug](https://user-images.githubusercontent.com/59312982/92657784-b07b4780-f2f5-11ea-9466-f8cf9947d732.jpg)

**Comment by chengy77** [comment]
I too seem to be having a similar issue. I'm sending temperature readings to another Pi using MQTT. I get the initial reading when Deploying but nothing after that, even when the temperature changes. Here's the Log. Any thoughts?
eb2c9345-7547-4583-9377-ec6a4258dbe0 10:29:39 AM: debug /smartthings/webhook
eb2c9345-7547-4583-9377-ec6a4258dbe0 10:29:39 AM: debug 0758
eb2c9345-7547-4583-9377-ec6a4258dbe0 10:29:39 AM: debug C0A80019
eb2c9345-7547-4583-9377-ec6a4258dbe0 10:29:39 AM: debug Local POST fallback

**Comment by otaviojr** [comment]
I've uploaded a new version of this module using the new SmartThings architecture. Webhook has changed a little with this new version. I think it will be easier to make it works now. Maybe, you want to give it a try.

Regards
