### ISSUE TITLE
Unable to install SmartThings

### ISSUE THREAD

**Issue by ghost** [otaviojr/node-red-contrib-smartthings#54]
I have installed Node red on my Ubuntu 20.04
I have installed alexa palette but when I try to install SmartThings palette I have this error:

> 2021-02-28T05:23:13.949Z Install : node-red-contrib-smartthings 0.0.20

> 2021-02-28T05:23:13.956Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-smartthings@0.0.20
> 2021-02-28T05:23:15.416Z [err] npm 
> 2021-02-28T05:23:15.416Z [err] ERR! code ENOENT
> 2021-02-28T05:23:15.416Z [err] npm 
> 2021-02-28T05:23:15.416Z [err] ERR! syscall
> 2021-02-28T05:23:15.416Z [err]  spawn git
> 2021-02-28T05:23:15.416Z [err] npm
> 2021-02-28T05:23:15.416Z [err]  ERR!
> 2021-02-28T05:23:15.416Z [err]  path
> 2021-02-28T05:23:15.416Z [err]  git
> 2021-02-28T05:23:15.416Z [err] npm 
> 2021-02-28T05:23:15.417Z [err] ERR! 
> 2021-02-28T05:23:15.417Z [err] errno
> 2021-02-28T05:23:15.417Z [err]  ENOENT
> 2021-02-28T05:23:15.419Z [err] npm
> 2021-02-28T05:23:15.419Z [err]  ERR! enoent Error while executing:
> 2021-02-28T05:23:15.419Z [err] npm ERR! 
> 2021-02-28T05:23:15.419Z [err] enoent undefined ls-remote -h -t https://github.com/otaviojr/smartthings-node.git
> 2021-02-28T05:23:15.419Z [err] npm
> 2021-02-28T05:23:15.419Z [err]  ERR! 
> 2021-02-28T05:23:15.420Z [err] enoent
> 2021-02-28T05:23:15.420Z [err]  
> 2021-02-28T05:23:15.420Z [err] npm ERR! enoent 
> 2021-02-28T05:23:15.420Z [err] npm ERR! enoent spawn git ENOENT
> 2021-02-28T05:23:15.420Z [err] npm ERR! enoent This is related to npm not being able to find a file.
> 2021-02-28T05:23:15.420Z [err] npm ERR! enoent 
> 2021-02-28T05:23:15.426Z [err] 
> 2021-02-28T05:23:15.426Z [err] npm ERR! A complete log of this run can be found in:
> 2021-02-28T05:23:15.426Z [err] npm ERR!     /root/snap/node-red/675/.npm/_logs/2021-02-28T05_23_15_421Z-debug.log
> 2021-02-28T05:23:15.430Z rc=1

Can you help me?

**Comment by otaviojr** [comment]
install git

**Comment by Giamma1963** [comment]
I installed git and this is the log:

> 2021-03-02T05:37:41.349Z Install : node-red-contrib-smartthings 0.0.20
> 
> 2021-03-02T05:37:41.356Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-smartthings@0.0.20
> 2021-03-02T05:37:43.613Z [err] npm
> 2021-03-02T05:37:43.613Z [err]  ERR! code ENOENT
> 2021-03-02T05:37:43.613Z [err] npm ERR! syscall spawn git
> 2021-03-02T05:37:43.613Z [err] npm 
> 2021-03-02T05:37:43.613Z [err] ERR! path git
> 2021-03-02T05:37:43.613Z [err] npm
> 2021-03-02T05:37:43.614Z [err]  ERR! errno
> 2021-03-02T05:37:43.614Z [err]  ENOENT
> 2021-03-02T05:37:43.615Z [err] npm
> 2021-03-02T05:37:43.615Z [err]  ERR! enoent Error while executing:
> 2021-03-02T05:37:43.615Z [err] npm ERR! enoent
> 2021-03-02T05:37:43.616Z [err]  undefined ls-remote -h -t https://github.com/otaviojr/smartthings-node.git
> 2021-03-02T05:37:43.616Z [err] npm 
> 2021-03-02T05:37:43.616Z [err] ERR! enoent
> 2021-03-02T05:37:43.616Z [err]  
> 2021-03-02T05:37:43.616Z [err] npm 
> 2021-03-02T05:37:43.616Z [err] ERR! enoent
> 2021-03-02T05:37:43.616Z [err]  
> 2021-03-02T05:37:43.616Z [err] npm
> 2021-03-02T05:37:43.616Z [err]  ERR! 
> 2021-03-02T05:37:43.616Z [err] enoent spawn git ENOENT
> 2021-03-02T05:37:43.616Z [err] npm 
> 2021-03-02T05:37:43.616Z [err] ERR! enoent
> 2021-03-02T05:37:43.616Z [err]  This is related to npm not being able to find a file.
> 2021-03-02T05:37:43.616Z [err] npm 
> 2021-03-02T05:37:43.616Z [err] ERR! enoent
> 2021-03-02T05:37:43.616Z [err]  
> 2021-03-02T05:37:43.622Z [err] 
> 2021-03-02T05:37:43.622Z [err] npm
> 2021-03-02T05:37:43.622Z [err]  ERR! A complete log of this run can be found in:
> 2021-03-02T05:37:43.622Z [err] npm ERR!
> 2021-03-02T05:37:43.622Z [err]      /root/snap/node-red/675/.npm/_logs/2021-03-02T05_37_43_617Z-debug.log
> 2021-03-02T05:37:43.628Z rc=1
