### ISSUE TITLE
Button support

### ISSUE THREAD

**Issue by JasonKChow** [otaviojr/node-red-contrib-smartthings#6]
I recently got a Smartthings button. There does not appear to be support for it, can it be added? The button supports single press, double press, and long press (hold).

**Comment by otaviojr** [comment]
I have some myself and I forgot them.

Two days ago I decided to move some rules from smartthings to nodered and what?

So yes, I'm doing it! :-)

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
I pushed a new npm version with button support.

Please, update your smartapp the get the button number.

regards,
Otávio Ribeiro

**Comment by JasonKChow** [comment]
Looks good!
