### ISSUE TITLE
Unable to install Smartthings

### ISSUE THREAD

**Issue by sfuller5641** [otaviojr/node-red-contrib-smartthings#60]
I have tried the install but get the following:

C:\WINDOWS\system32> npm install node-red-contrib-smartthings
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simon\AppData\Local\npm-cache\_logs\2021-08-14T22_53_53_829Z-debug.log

**Comment by otaviojr** [comment]
Install git...

**Comment by sfuller5641** [comment]
Hi,

I did npm install git but when I try again get the error

C:\WINDOWS\system32> npm install node-red-contrib-smartthings
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by otaviojr** [comment]
Git is not an npm package.

I do not use windows for a long time now, so I tried to find a tutorial on installing git on Windows.

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
https://phoenixnap.com/kb/how-to-install-git-windows

Regards

**Comment by sfuller5641** [comment]
Thanks, I did the npm install then also installed the git system via windows with the same error message when trying to install the smartthings package
