### ISSUE TITLE
Can't install Smartthings Classic app, is there any alternative?

### ISSUE THREAD

**Issue by obaldius** [otaviojr/node-red-contrib-smartthings#63]
The tittle is selfexplanatory. Can anybody help please?

**Comment by RenevdBroek** [comment]
You can use the web alternative @ https://my.smartthings.com/ to install the smartapp into your location. When you've installed it in the web version you'll see it in the new  smarttthings app on your phone.

/Rene

**Comment by obaldius** [comment]
sensor.webcore_tv_channel_name

> You can use the web alternative @ https://my.smartthings.com/ to install the smartapp into your location. When you've installed it in the web version you'll see it in the new smarttthings app on your phone.

Wow, I really appreciate your help but there's somethign that's pulling me back. I recently learned groovy or something like that is being shut down anytime soon and  so, smart apps will become useless. Are you aware of that? will this flow still work?

thanks in advanced

**Comment by RenevdBroek** [comment]
Yes, i've read the same announcement about the groovy IDE, by then hopefully somebody has rewritten this app.  For now though, I'm just happy it works as it does.

I found the option here. You do have to follow all the other instructions for the installation, only part for the classic app can be substituted with the web version. ( be sure to select your location first before jou add the smartapp and publish it in the groovy IDE, otherwise you won't see it as an available app in the web app version)
![image](https://user-images.githubusercontent.com/6630108/143538340-c5641406-03e6-4d04-85ca-125fc64d9282.png)

**Comment by obaldius** [comment]
@RenevdBroek thanks a lot for all the time you took to explain me everything. I appreciate

**Comment by RenevdBroek** [comment]
no problem.

**Comment by forziere** [comment]
HI i have installed your smartapp I set it . but when I trigger with my device I don't see any update in node red.
could you help me?

**Comment by forziere** [comment]
![image](https://user-images.githubusercontent.com/73720066/147926089-a41110fb-cf0a-40dc-956c-6c792fe148cd.png)

**Comment by forziere** [comment]
![image](https://user-images.githubusercontent.com/73720066/147926296-142f53e7-1eb2-4e9e-998f-a90d67759201.png)

**Comment by otaviojr** [comment]
I'm working on a new version where the nodered module is also a new hosted smartapp. In doing so, will be possible to register the smartapp inside the new developer portal and use the new smartthings application to handle it.

The problem, no more local network option and you will need a domain and a SSL to make it work properly.

I already have a branch(smartapp-builtin) working with this new approach.

It can be registered here: https://smartthings.developer.samsung.com/

Just create a new automation project. Register the app as a webhook endpoint. And, in the target address, use https://your-nodered-domain/smartthings/smartapp.

Change the app status to Deployed to test

You will have to put your new smartthings app into development mode. I think that holding the "About Smartthings" on the menu for 5 seconds will unlock the developer mode option. Enable it and you will see the smartapp in your new Smartthing app.

Configure it with the devices you want to receive events and it's done.

It's a way of doing this with smartthings new infrastructure... I don't figure out a better way for now.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
https://www.noip.com has SSL certificates included on all plans
