### ISSUE TITLE
update nodered

### ISSUE THREAD

**Issue by forziere** [otaviojr/node-red-contrib-smartthings#66]
HI i have installed your smartapp I set it . but when I trigger with my device I don't see any update in node red.
could you help me?

**Comment by forziere** [comment]
![image](https://user-images.githubusercontent.com/73720066/147931710-3c538212-4021-41c3-96bb-5279e2b36db5.png)

**Comment by forziere** [comment]
this is my node red whitout any update after a trigger

**Comment by forziere** [comment]
![image](https://user-images.githubusercontent.com/73720066/147931955-63ed6129-725d-4acc-8580-a688c84645d8.png)

**Comment by harvybob** [comment]
Did you manage to resolve this?
