### ISSUE TITLE
End of Groovy and SmartApps. Will the palette continue to work? 

### ISSUE THREAD

**Issue by reinaldots** [otaviojr/node-red-contrib-smartthings#69]
As informed by the SmartThings developers, the Groovy language and smartapps will end in SmartThings with the switch to Edge/Lua platform and locally running drivers.

Are there plans for the node-red-contrib-smartthings palette to work without relying on the SmartApp NodeRed WebHook?

**Comment by NTexasMom** [comment]
Do you have node-red-contrib-smartthings working with the SmartApp NodeRed WebHook? I am not sure if I am running into problems because SmartThings has stopping allowing the use of WebHook. I am interested in this topic since I am trying to use NodeRed for automations. Any recommendations on another way to GET/POST messages from devices on local network if not through WebHook?

**Comment by otaviojr** [comment]
Hi, when using webhook we have the local network option. 

But, webhooks in the way we are using them today are dying. 

As a solution, I'm working on a new version where the nodered module is also a new hosted smartapp. In doing so, will be possible to register the smartapp inside the new developer portal and use the new smartthings application to handle it. 

The problem, no more local network option and you will need a domain and a SSL to make it work properly.

I already have a branch(smartapp-builtin) working with this new approach. 

It can be registered here: https://smartthings.developer.samsung.com/

Just create a new automation project. Register the app as a webhook endpoint. And, in the target address, use https://your-nodered-domain/smartthings/smartapp.

Change the app status to Deployed to test

You will have to put your new smartthings app into development mode. I think that holding the "About Smartthings" on the menu for 5 seconds will unlock the developer mode option. Enable it and you will see the smartapp in your new Smartthing app.

Configure it with the devices you want to receive events and it's done.

It's a way of doing this with smartthings new infrastructure... I don't figure out a better way for now.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
https://www.noip.com has SSL certificates included on all plans

**Comment by otaviojr** [comment]
> Thank you Otavio. This information is timely for me because my node-red is no longer getting notifications of state changes to my sensors from Smartthings, whether I use a local IP address or a public IP address (via duckdns), and I was getting ready to move away from the Samsung Smartthings hub to a Zigbee to MQTT bridge. Webhook just misteriously stopped working! I would like you try out your new smartthings module. How do you recommend that I select and install your new branch (smartapp-builtin)?

Hi @vicente95650 ,

on your NodeRed package.json do something like this:

    "dependencies": {
        ...
        "node-red-contrib-smartthings": "https://github.com/otaviojr/node-red-contrib-smartthings.git#smartapp-builtin",
        ...
    },

That will be enough to install the new version from the smartapp-builtin branch.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
@vicente95650 I've just created a new version of the npm package. And updated the master branch. You could install it as you have done before and probably will get the latest package version.

**Comment by vicente95650** [comment]
oh nice,  because I could not get past the "Verify App Registration" step. I  don't know how to determine what branch of node-red-contrib-smartthings I am actually using in node-red but did notice that node-red did not ask me to deploy any nodes that existed in my flow. I will reinstall your node-red module using npm install node-red-contrib-smartthings after editing dependencies in my package.json file to remove the node-red-contrib-smartthings line that I had added.  I will let you know tomorrow if I am successful.

**Comment by vicente95650** [comment]
@otaviojr I was able to try a fresh install from the Master branch which you just updated and I still cannot get past the "Verify App Registration" step. I will troubleshoot some more later today. Thank you for updating this and for your help.

**Comment by otaviojr** [comment]
@vicente95650 what url are you using? 

You can verify it using your browser. 

You will get something like this:

"SmartThings NodeRed SmartApp is accessible."

![Screenshot from 2022-06-06 21-00-57](https://user-images.githubusercontent.com/2933837/172268427-d0093672-6028-48d3-a24f-2f935b1a8f77.png)

Don't forget that using dynamic IP, sometimes, the port 80 is blocked.

regards,
Otávio Ribeiro

**Comment by vicente95650** [comment]
@otaviojr  I am using the URL  https://vvcsmartthings.duckdns.org/smartthings/smartapp. When I use curl to test (from an external system)  the URL apparently reaches your node.  I  get the response "smartthings nodered smartapp is accessible".  I  still however cannot get past the "verify app registration" step!

**Comment by otaviojr** [comment]
@vicente95650 Ok, I forgot a step, can you get a look at your NodeRed console messages? Click on verify and look at the console. There will be a message there with a URL. Can you copy and paste it at your browser?

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
@vicente95650 node-red-contrib-smartthings@0.0.32 will call the registration URL without any further work.

Could you please update your version and give it a try?

regards,
Otávio Ribeiro

**Comment by vicente95650** [comment]
@otaviojr I followed your instructions and I was able to change status of the smartapp to "deployed to test" and I can now verify the URL using a web browser or using curl. I have installed the smartapp (in the smartthings app on my iphone) . My smartthing nodes however do not appear to be receiving notifications of state changes. I have not generated a new token. I am still using my original one.

**Comment by otaviojr** [comment]
Did you select all your devices at the Smartthing App?

![WhatsApp Image 2022-06-07 at 11 38 17](https://user-images.githubusercontent.com/2933837/172408301-762766f1-9dee-430f-846d-5737cbacce7f.jpeg)

regards,
Otávio Ribeiro

**Comment by vicente95650** [comment]
Yes I did but I will try again.

**Comment by vicente95650** [comment]
@otaviojr You were right, I had not properly selected all devices. Everything works now! Eureka! Thank you very much!

**Comment by vicente95650** [comment]
By the way I installed your latest module using npm install node-red-contrib-smartthings@0.0.32 as you instructed. Was that the Master branch?

**Comment by otaviojr** [comment]
Excellent news. Thank you for being so patient in helping me test this new code.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
> By the way I installed your latest module using npm install node-red-contrib-smartthings@0.0.32 as you instructed. Was that the Master branch?

yes

**Comment by vicente95650** [comment]
@otaviojr You probably have this in your "todo" list but, just in case you don't, I wanted to point out that in the documentation for each node you make no mention of the new "pull" input. In your previous version you only had an  "update" input.

**Comment by otaviojr** [comment]
> @otaviojr You probably have this in your "todo" list but, just in case you don't, I wanted to point out that in the documentation for each node you make no mention of the new "pull" input. In your previous version you only had an "update" input.

@vicente95650 I don't, that was a contribution, and I forgot to update the documentation. I will work on it. Thanks.

**Comment by otaviojr** [comment]
@vicente95650 I've updated the documentation with the pull input topic and released a new version

**Comment by vicente95650** [comment]
@otaviojr I tried updating ( npm update node-red-contrib-smartthings) and installing (npm install node-red-contrib-smartthings) and the node documentation still only shows the "update" input but not the "pull" input.

**Comment by vicente95650** [comment]
perhaps I dont really understand which version of your code I am actually using.

**Comment by vicente95650** [comment]
In my package.json file I see this line:
 "node-red-contrib-smartthings": "^0.0.32"

**Comment by otaviojr** [comment]
The latest version is the 0.0.33.

But the only correction is the pull documentation.

regards,
Otávio Ribeiro

**Comment by vicente95650** [comment]
I tried
npm install node-red-contrib-smartthings@0.0.33 and still don't see the change to the documentation. For example the motion node shows only one input topic: update.

**Comment by vicente95650** [comment]
I tried installing your latest code by using  the node-red palette (which now showed an update was available)  and now I do see the documentation has been updated. Thanks again.
