### ISSUE TITLE
Problem with SmartApp communicating with NodeRed

### ISSUE THREAD

**Issue by gcaley** [otaviojr/node-red-contrib-smartthings#7]
Hi there, thanks for the previous help.

I can now deploy a smartthings sensor and when i connect to debug and deploy, then i see the sensor readings etc. All good.

I dont however see any new updates from the sensor, unless i re-deploy the flow.

Ive followed the steps to test the smartapp using the simulator in the ST-IDE, and in the debug box i see the following when i, for example, turn a switch on. It looks like the ip and port,in hex, but no other obvious error. 

Any ideas? thanks.

44b0879b-7700-4322-8752-3c49bf37c251 17:08:13: debug /smartthings/webhook
44b0879b-7700-4322-8752-3c49bf37c251 17:08:13: debug 0050
44b0879b-7700-4322-8752-3c49bf37c251 17:08:13: debug C0A801BF
44b0879b-7700-4322-8752-3c49bf37c251 17:08:13: debug Local POST fallback

**Comment by branteforest** [comment]
I am having the exact same issue. Using multi-sensor, arrival and motion sensors,

**Comment by mane-wt** [comment]
I also have the exact same issue. I do hope it it fixable because this is the node I really woluld like to use.
Have tested with buttons/motion sensors, aircondition, lamps, I can see output from the sensors only ince when I deploy the flow, can not update or control anything after that.

**Comment by branteforest** [comment]
Hi Guys. I think I have figured it out. You have to implement the SmartApp portion doing a callback to the webhook on NodeRed. I dont have it working yet, as it seems SamrtThings are not accepting self-signed certificates

**Comment by branteforest** [comment]
I can confirm. Following the instruction on the SmartApp solved the update problem. I got it to work perfectly

**Comment by otaviojr** [comment]
@branteforest Have you tried local address with http instead of https?

I believe that local requests can be done using http.

Remote requests must be done with https and need a valid certificate.

regards,
Otávio Ribeiro

> Hi Guys. I think I have figured it out. You have to implement the SmartApp portion doing a callback to the webhook on NodeRed. I dont have it working yet, as it seems SamrtThings are not accepting self-signed certificates

**Comment by otaviojr** [comment]
@gcaley have you fixed this issue?

regards,
Otávio Ribeiro

**Comment by gcaley** [comment]
> @gcaley have you fixed this issue?
> 
> regards,
> Otávio Ribeiro

Ive moved to Hubitat now. Thanks anyway.

**Comment by mane-wt** [comment]
Hi, I have updated node-red-contrib-smartthings to ver 0.0.13 and I have also double checked that I have the latest SmartApp code. I have also tried debug the SmartApp and then I got similiar 4 lines as above but never any updates in Node-Red. Any Idéas?
