### ISSUE TITLE
ST Webhook generating debug messages but nothing received in NodeRed

### ISSUE THREAD

**Issue by NTexasMom** [otaviojr/node-red-contrib-smartthings#70]
Hello, I have followed through the tutorial and problem fix posts on several forums, but I am stuck and not sure what to do next to resolve my issue.

I have a Raspberry Pi 4B 8GB. I have Docker with NodeRed, Mosquitto, InfluxDB, Grafana, and Portainer containers. Everything is installed and running. When I noticed the SmartThings node in NodeRed, I was super excited. I installed it. I logged on to SmartThings IDE and created/published/installed Webhook by Otávio Ribeiro. I went to my mobile device and added in the Webhook SmartApp. I am using local network, 192.168.1.x:1880/smartthings/webhook URL.

When I manually turn a light switch on/off, the appropriate debug commands print out in ST Live Logging. I believe that the webhooks smartapp is working properly. In NodeRed, I have a ST OnOff node with output going to a debug node just to test that messages are being received properly. When I deploy the flow, I receive the initial debug statement with accurate payload message (light on or off). But as the device's state is manually changed, only ST SmartApp Live Logging displays any debug messages. The state is correct there, but NodeRed receives no updates.

I have followed the trouble shooting posts that I have seen. I do not see anything wrong. I've actually removed and recreated/published/installed webhook several times to make sure that I followed instructions exactly. I still have the same result. Any assistance would be GREATLY appreciated!

**Comment by otaviojr** [comment]
Hi, I think your IP address must be a valid one, accessible by smartthings, with a domain and a valid SSL in order for the webhook to work properly.

**Comment by otaviojr** [comment]
I've uploaded a new version of this module. With the new module, using the new SmartThings architecture, the webhook interface has changed a little. It could be easier to make it works now. Maybe, you want to give it a try.
