### ISSUE TITLE
Missing sensors node for "acceleration" and "3-axis"

### ISSUE THREAD

**Issue by sdalu** [otaviojr/node-red-contrib-smartthings#73]
The Aeotec Multi purpose sensor ( https://aeotec.com/products/aeotec-multipurpose-sensor/ ), include various sensors such as temperature, open-door, acceleration, 3-axis. But I only found nodes for temperature and open-door.

If it helps, here are debugging message for the missing nodes:

* 3-axis
~~~
{
  id: '85272aa2-78db-4e80-8585-849469710190',
  date: '2022-06-06T08:22:58.056Z',
  value: [ -1004, 120, 60 ],
  name: 'threeAxis',
  display_name: 'Door watcher',
  description: 'Door watcher was [-1004,120,60]mG',
  source: 'DEVICE',
  state_changed: true,
  physical: false,
  location_id: '18dc1fb8-d184-4e05-8c0b-c0d31941a298',
  hub_id: '9762c497-3d41-48e8-a1f7-aa733a3f8315'
}
~~~

* acceleration
~~~
{
  id: '85272aa2-78db-4e80-8585-849469710190',
  date: '2022-06-06T08:23:08.156Z',
  value: 'inactive',
  name: 'acceleration',
  display_name: 'Door watcher',
  description: 'Door watcher was inactive',
  source: 'DEVICE',
  state_changed: true,
  physical: false,
  location_id: '18dc1fb8-d184-4e05-8c0b-c0d31941a298',
  hub_id: '9762c497-3d41-48e8-a1f7-aa733a3f8315'
}
~~~

**Comment by otaviojr** [comment]
Hi @sdalu,

the node-red-contrib-smartthings@0.0.34 has a first implementation of the ThreeAxis sensor, but, I do not have one, so, I've developed it using your output.

Could you please give it a try?

I wait your feedback to do any corrections.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
@sdalu After the 0.30 version, things have changed a little. You must reconfigure your smartapp in order to receive events from SmartThings. 

We have new instructions on Github's page. 

regards,
Otávio Ribeiro

**Comment by sdalu** [comment]
Thanks, the threeAxis is working (tested with update only). I will do further testing tomorrow with the smartapp.
Could you also add the "acceleration" detection which is used to detect knocking on the door

**Comment by otaviojr** [comment]
@sdalu It is done. If you update to the latest version it should appears to you.

Regards

**Comment by sdalu** [comment]
@otaviojr I was on 0.0.34, I will upgrade to 0.0.36

**Comment by sdalu** [comment]
@otaviojr tested with the smartapp. Looks good.
