### ISSUE TITLE
What permissions are necessary when creating the token?

### ISSUE THREAD

**Issue by Humancell** [otaviojr/node-red-contrib-smartthings#77]
When creating a new token SmartThings now provides extremely granular permissions.  What is the absolutely minimum permissions required for the app to work correctly?

Thank you for creating this!  I can't wait to give it a try!

**Comment by otaviojr** [comment]
I will be honest with you, I usually select every one of them. :-)

But, many of them are not necessary,

I guess that the minimal set of permissions is:

- devices
- locales
- scenes
- device profiles

Try with those, but, if something doesn't work as expected you may try some others.

Regards,
Otávio Ribeiro

**Comment by Humancell** [comment]
Thank you ... I did end up selecting them all just to get it working.  :-)

**Comment by otaviojr** [comment]
@Humancell, I edited my previous answer to include a more granular selection.

Regards
