### ISSUE TITLE
No Power or Energy Info

### ISSUE THREAD

**Issue by ELLISMD65** [otaviojr/node-red-contrib-smartthings#8]
I have the aeotec smart plug 6, and when i receive trigger info, there is no info on power, energy or device mode, from any of the nodes, that i can use or update.

**Comment by otaviojr** [comment]
Hi @ELLISMD65,

I will implement the power node. Just give me a couple of days.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
I've implemented a Power Meter node at 0.0.14.

Could you give it a try?

regards,
Otávio Ribeiro

**Comment by ELLISMD65** [comment]
works great, thanks for your time and effort making a great app
