### ISSUE TITLE
SmartApp "Problems connecting. Check your internet and try again"

### ISSUE THREAD

**Issue by DuMees** [otaviojr/node-red-contrib-smartthings#89]
Am I the only one experiencing an error when you try to add the Smartapp (the one from the developer.samsung.com step) (or modify) to register the device to receive statuses from?

Did they change something?

**Comment by goblins74** [comment]
Hi,

Same problem for me :(

**Comment by DuMees** [comment]
If you remove the app via samsung developer portal, you'll than get the option to add it again (you can only have 1 of this kind). Now it works again.

**Comment by goblins74** [comment]
Thanks for your reply
In fact registration of my smartapp works well on samsung site; When I want to add this in the android Smartthings app I can see and click on it but get an error : connection problem ....
