### ISSUE TITLE
dead link in node red library

### ISSUE THREAD

**Issue by teslawave** [otaviojr/node-red-contrib-smartthings#9]
hey didn't know how to contact you from the node red side of things but the link for the smart app code is not working, i found it here but for those coming from node red it was a dead end.

https://flows.nodered.org/smartapp/webhook.groovy?raw=true

**Comment by otaviojr** [comment]
I've uploaded a new version with the link problem fixed.

regards

**Comment by otaviojr** [comment]
Hi, thanks for the report. I uploaded a new version with the link problem fixed.

regards,
Otávio Ribeiro
