### ISSUE TITLE
SmartThings Thermostat node is failing with an error that the `thermostat` capability is not a valid value

### ISSUE THREAD

**Issue by johnwalicki** [otaviojr/node-red-contrib-smartthings#90]
The Thermostat node is failing with an error that the `thermostat` capability is not a valid value.

```
"Error: Request failed with status code 422: {"requestId":"213B4DE8-7542-462B-A461-A747B9652BD5","error":{"code":"ConstraintViolationError","message":"The request is malformed.","details":[{"code":"NotValidValue","target":"commands[0].capability","message":"thermostat is not a valid value.","details":[]}]}}"
```
I checked the [SmartThings Documentation](https://developer.smartthings.com/docs/devices/capabilities/capabilities-reference#thermostatHeatingSetpoint) and see that the `capability` should be `thermostatHeatingSetPoint`

I have prepared a PR which fixes the `capability` for the various Thermostat capabilities.
The PR modifies the `smartthings/smartthings-thermostat.js` file.

**Comment by johnwalicki** [comment]
I tested on my local Node-RED instance and the error is resolved with this patch.

**Comment by johnwalicki** [comment]
@otaviojr - When you return from your holiday break, can you take a look at my PR?  It fixes this problem.  Would like to see it merged upstream so I can move off my private fork.

**Comment by otaviojr** [comment]
John,

I managed to merge your code.

Sorry about the delay.

Thanks for helping!

An amazing 2023 for you with lots of code! :-)

regards,
Otávio Ribeiro
